### ISSUE TITLE
Unable to set an expiration longer than 6 hours

### ISSUE THREAD

**Issue by mhuggins7278** [glg/jwt-generator#1]
Following the documentation I've tried setting expiration at 24h, 7d and the token that comes back in both cases is set to expire in 6h.

**Comment by mhuggins7278** [comment]
So after reading the code it's just an issue with the documentation the docs say to use '&expires=duration' but the code is looking for &expiration=duration  using expiration works just fine

**Comment by asegal** [comment]
Ugh.  sorry about that.  have fixed the docs.
